[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
combine_as_imports = true
known_first_party = ["app"]
known_third_party = ["flask", "pydantic", "sqlalchemy", "flasgger"]
