AWSTemplateFormatVersion: '2010-09-09'
Description: Secrets Manager secret for DB credentials

Parameters:
  DBUsername:
    Type: String
  DBPassword:
    Type: String
    NoEcho: true
  DBHost:
    Type: String
  DBName:
    Type: String

Resources:
  FruitstoreDBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: fruitstore/db_credentials
      Description: Database credentials for Fruitstore app
      SecretString: !Sub |
        {
          "DB_USER": "${DBUsername}",
          "DB_PASS": "${DBPassword}",
          "DB_HOST": "${DBHost}",
          "DB_NAME": "${DBName}"
        }
      Tags:
        - Key: Name
          Value: FruitstoreDBSecret

Outputs:
  SecretArn:
    Value: !Ref FruitstoreDBSecret
    Export:
      Name: FruitstoreSecretArn
