name: Deploy Full Infrastructure

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy VPC
        run: |
          aws cloudformation deploy \
            --stack-name fruitstore-vpc \
            --template-file cloudformation/vpc_template.yml \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Deploy Security Group & IAM Roles
        run: |
          aws cloudformation deploy \
            --stack-name fruitstore-security \
            --template-file cloudformation/security_template.yml \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Deploy Aurora DB Cluster
        run: |
          aws cloudformation deploy \
            --stack-name fruitstore-db \
            --template-file cloudformation/db_template.yml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              DBUsername=fruituser \
              DBPassword=SuperSecurePass123

      - name: Deploy Secrets
        run: |
          aws cloudformation deploy \
            --stack-name fruitstore-secrets \
            --template-file cloudformation/secrets_template.yml \
            --parameter-overrides \
              DBUsername=fruituser \
              DBPassword=SuperSecurePass123 \
              DBHost=fruitstore-cluster.cluster-c69cq4mcm794.us-east-1.rds.amazonaws.com \
              DBName=fruitstore

      - name: Deploy EC2 Instance
        run: |
          aws cloudformation deploy \
            --stack-name fruitstore-ec2 \
            --template-file cloudformation/ec2_template.yml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              KeyName=${{ secrets.KEY_NAME }} \
              LatestReleaseTag=latest

      - name: Deploy CloudWatch Logs Group
        run: |
          aws cloudformation deploy \
            --stack-name fruitstore-cloudwatch \
            --template-file cloudformation/cloudwatch_template.yml
