name: Deploy Full Infrastructure

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::611771051034:role/github-actions-deployment-role
          aws-region: us-east-1

      - name: Deploy CloudFormation Stack via AWS CLI
        run: |
          aws cloudformation deploy \
            --stack-name fruitstore-ec2-stack \
            --template-file cloudformation/templates/template.json \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides InstanceType=t2.micro \
            --tags Project=FruitStore Environment=Dev
